export const gridItems = [
  {
    id: 1,
    title: 'Click The Cookie!',
    description: '',
    className: 'md:col-span-1 flex flex-col items-center justify-center',
    imgClassName: 'w-20 h-20 md:w-36 md:h-36',
    titleClassName: '__#th Click',
    img: '/wajeehscookie.png',
    spareImg: '',
  },
  {
    id: 2,
    title: '',
    description: '',
    className: 'md:col-span-1 flex justify-center items-center relative',
    imgClassName: '',
    titleClassName: '',
    img: '',
    spareImg: '',
  },
  {
    id: 3,
    title:
      'Tech enthusiast with a passion for development. \n**See projects below!**',
    description: '',
    className:
      'md:col-span-1 flex items-center justify-center transition-transform duration-300 ease-in-out hover:scale-105 hover:rotate-1 hover:shadow-[0px_4px_15px_rgba(93,188,252,0.5)]',
    imgClassName: '',
    titleClassName: 'text-left',
    img: '/grid.svg',
    spareImg: '/b4.svg',
  },
  {
    id: 4,
    title: 'Connect With Me - Overridden',
    description: '',
    className: 'md:col-span-1 flex items-center justify-center',
    imgClassName: '',
    titleClassName: '',
    img: '',
    spareImg: '',
  },
  {
    id: 5,
    title: 'Want to Work Together?',
    description: '',
    className: 'md:col-span-2 flex justify-center items-center',
    imgClassName: '',
    titleClassName: 'justify-center md:max-w-full max-w-60 text-center',
    img: '',
    spareImg: '',
  },
];